import type {
  NewsItem,
  WhaleTransaction,
  ETFFlow,
  Liquidation,
  LaneOutput,
} from "./types";

export const MOCK_NEWS: NewsItem[] = [
  {
    id: "1",
    location: "Mumbai",
    country: "India",
    timeAgo: "12m ago",
    headline: "RBI signals cautious stance on crypto regulation framework",
    source: "Reuters",
    sentiment: "bearish",
    marketTag: "INR markets",
    connected: 4,
    lat: 19.076,
    lng: 72.8777,
  },
  {
    id: "2",
    location: "New York",
    country: "USA",
    timeAgo: "28m ago",
    headline: "BlackRock IBIT records $420M net inflow — largest single-day since launch",
    source: "Bloomberg",
    sentiment: "bullish",
    marketTag: "ETF flows",
    connected: 7,
    lat: 40.7128,
    lng: -74.006,
  },
  {
    id: "3",
    location: "Singapore",
    country: "Singapore",
    timeAgo: "45m ago",
    headline: "Major exchange adds SOL staking products for institutional clients",
    source: "CoinDesk",
    sentiment: "bullish",
    marketTag: "SOL ecosystem",
    connected: 3,
    lat: 1.3521,
    lng: 103.8198,
  },
  {
    id: "4",
    location: "Frankfurt",
    country: "Germany",
    timeAgo: "1h ago",
    headline: "ECB minutes hint at extended pause on rate cuts amid inflation stickiness",
    source: "Financial Times",
    sentiment: "neutral",
    marketTag: "Macro / EUR",
    connected: 5,
    lat: 50.1109,
    lng: 8.6821,
  },
  {
    id: "5",
    location: "Seoul",
    country: "South Korea",
    timeAgo: "1h ago",
    headline: "Upbit volume surges 38% as altcoin rotation accelerates",
    source: "The Block",
    sentiment: "bullish",
    marketTag: "KRW markets",
    connected: 2,
    lat: 37.5665,
    lng: 126.978,
  },
  {
    id: "6",
    location: "London",
    country: "UK",
    timeAgo: "2h ago",
    headline: "FCA issues warning on unregistered DeFi yield platforms",
    source: "Cointelegraph",
    sentiment: "bearish",
    marketTag: "DeFi regulation",
    connected: 6,
    lat: 51.5074,
    lng: -0.1278,
  },
  {
    id: "7",
    location: "Tokyo",
    country: "Japan",
    timeAgo: "2h ago",
    headline: "Metaplanet adds another 1,111 BTC to corporate treasury holdings",
    source: "CoinDesk",
    sentiment: "bullish",
    marketTag: "BTC treasury",
    connected: 5,
    lat: 35.6762,
    lng: 139.6503,
  },
  {
    id: "8",
    location: "Dubai",
    country: "UAE",
    timeAgo: "3h ago",
    headline: "VARA grants new licenses to two institutional crypto custody firms",
    source: "Decrypt",
    sentiment: "bullish",
    marketTag: "MENA regulation",
    connected: 3,
    lat: 25.2048,
    lng: 55.2708,
  },
  {
    id: "9",
    location: "Hong Kong",
    country: "Hong Kong",
    timeAgo: "3h ago",
    headline: "Spot ETH ETF filings draw renewed interest after weekend rebound",
    source: "Bloomberg",
    sentiment: "bullish",
    marketTag: "ETH ETFs",
    connected: 4,
    lat: 22.3193,
    lng: 114.1694,
  },
  {
    id: "10",
    location: "São Paulo",
    country: "Brazil",
    timeAgo: "4h ago",
    headline: "B3 exchange expands crypto derivatives offering for retail traders",
    source: "Reuters",
    sentiment: "neutral",
    marketTag: "LATAM markets",
    connected: 2,
    lat: -23.5505,
    lng: -46.6333,
  },
  {
    id: "11",
    location: "Zurich",
    country: "Switzerland",
    timeAgo: "5h ago",
    headline: "Swiss banks report rising demand for Bitcoin custody among private clients",
    source: "Financial Times",
    sentiment: "bullish",
    marketTag: "Institutional",
    connected: 4,
    lat: 47.3769,
    lng: 8.5417,
  },
  {
    id: "12",
    location: "Washington",
    country: "USA",
    timeAgo: "6h ago",
    headline: "Senate committee schedules hearing on stablecoin reserve transparency",
    source: "The Block",
    sentiment: "neutral",
    marketTag: "US policy",
    connected: 8,
    lat: 38.9072,
    lng: -77.0369,
  },
];

export const MOCK_LANES: LaneOutput[] = [
  {
    lane: "Technical",
    badge: "T",
    bias: "BULL",
    tier: "HIGH",
    reasoning: [
      "Price above 50/200 EMA crossover",
      "RSI(14) at 58 — room to run",
      "MACD histogram turning positive",
    ],
  },
  {
    lane: "Flow",
    badge: "F",
    bias: "BULL",
    tier: "MODERATE",
    reasoning: [
      "Open interest +4.2% in 24h",
      "Funding rate mild at 0.008%",
      "Long/short ratio 1.18",
    ],
  },
  {
    lane: "Narrative",
    badge: "N",
    bias: "MIXED",
    tier: "MODERATE",
    reasoning: [
      "ETF inflows positive but slowing",
      "Fed rhetoric hawkish-leaning",
      "Social sentiment 62% bullish",
    ],
  },
  {
    lane: "Macro",
    badge: "M",
    bias: "BEAR",
    tier: "LOW",
    reasoning: [
      "DXY strengthening +0.3%",
      "S&P 500 flat — risk-off undertone",
      "Gold +0.8% — hedge demand rising",
    ],
  },
];

export const MOCK_WHALES: WhaleTransaction[] = [
  {
    id: "w1",
    address: "0x8f2a…3c1d",
    amount: "1,250 BTC",
    usdValue: "$118.5M",
    direction: "in",
    timeAgo: "8m ago",
    chain: "Bitcoin",
  },
  {
    id: "w2",
    address: "0x4b91…7e2a",
    amount: "45,000 ETH",
    usdValue: "$153.9M",
    direction: "out",
    timeAgo: "22m ago",
    chain: "Ethereum",
  },
  {
    id: "w3",
    address: "bc1q…xk9p",
    amount: "890 BTC",
    usdValue: "$84.4M",
    direction: "out",
    timeAgo: "41m ago",
    chain: "Bitcoin",
  },
  {
    id: "w4",
    address: "0x2e77…9f4c",
    amount: "2.1M SOL",
    usdValue: "$367.5M",
    direction: "in",
    timeAgo: "1h ago",
    chain: "Solana",
  },
];

export const MOCK_ETF_FLOWS: ETFFlow[] = [
  { ticker: "IBIT", name: "iShares Bitcoin Trust", netFlow: 420.5, date: "Today" },
  { ticker: "FBTC", name: "Fidelity Wise Origin", netFlow: 128.3, date: "Today" },
  { ticker: "GBTC", name: "Grayscale Bitcoin Trust", netFlow: -45.2, date: "Today" },
  { ticker: "ARKB", name: "ARK 21Shares Bitcoin", netFlow: 67.1, date: "Today" },
  { ticker: "ETHA", name: "iShares Ethereum Trust", netFlow: 89.6, date: "Today" },
];

export const MOCK_LIQUIDATIONS: Liquidation[] = [
  {
    id: "l1",
    exchange: "Binance",
    pair: "BTC/USDT",
    side: "long",
    amount: "$12.4M",
    timeAgo: "5m ago",
  },
  {
    id: "l2",
    exchange: "Bybit",
    pair: "ETH/USDT",
    side: "short",
    amount: "$8.1M",
    timeAgo: "18m ago",
  },
  {
    id: "l3",
    exchange: "OKX",
    pair: "SOL/USDT",
    side: "long",
    amount: "$3.6M",
    timeAgo: "34m ago",
  },
];

export const TRACKED_PAIRS = [
  "BTC/USDT",
  "ETH/USDT",
  "SOL/USDT",
  "BNB/USDT",
  "XRP/USDT",
];

export const CORRELATION_MATRIX: Record<string, number> = {
  "ETH/USDT": 0.88,
  "SOL/USDT": 0.82,
  "BNB/USDT": 0.75,
  "XRP/USDT": 0.71,
  "PAXG/USDT": -0.35,
};
