-- AlterTable
ALTER TABLE "verdict_features" ADD COLUMN "rsiMomentum" DOUBLE PRECISION,
ADD COLUMN "volatilityRegime" DOUBLE PRECISION,
ADD COLUMN "fundingRateRoc" DOUBLE PRECISION,
ADD COLUMN "oiRoc" DOUBLE PRECISION,
ADD COLUMN "fearGreedRoc" DOUBLE PRECISION;
